.travis.yml
molecule-syntaxcheck.yml

Adds syntax checking and ansible-lint.
This is expected to fail on travis with the current playbooks.

Travis syntax check and lint

---

.travis.yml
nightshade-web.yml
ome-dundeeomero.yml
requirements.yml

This PR builds on top of https://github.com/openmicroscopy/prod-playbooks/pull/4 - Not sure if this branch on the other branch is the right way to go about this. 
Merged in the .travis.yml from master to avoid conflicts, thanks to @jburel for the tip.

Nightshade to 540

---

nightshade-webclients.yml
ome-demoserver.yml
ome-dundeeomero.yml
requirements.yml
templates/omero-web-config-for-webapps_ns-web-pub.j2

OME Production Server OMERO upgrades (540-541)

OME Production Server OMERO upgrades (540-541)

---

ome-dundeeomero.yml

Workaround for https://github.com/openmicroscopy/ansible-role-omego/issues/2

ome-dundeeomero aka Nightshade: Force OMEGO version

---

ome-demoserver.yml
ome-dundeeomero.yml
requirements.yml

Also drop omego versions overriding in the server playbooks

Bump openmicroscopy.omego version to 0.1.1

---

.travis.yml
site.yml
templates/omero-web-config-default-viewer.j2
training-server.yml

See: https://github.com/ome/ansible-examples-omero/pull/8
NB: this description will be updated with testing instructions

training-server: migrate from examples

---

ome-demoserver.yml
ome-dundeeomero.yml
training-server.yml

Adjusted the comments around the `yum` install tasks to be more specific.

prod-playbooks: Adjusted comments

---

README.md

Suggested by @will-moore in https://github.com/openmicroscopy/ome-documentation/pull/1830#discussion_r162601924
cc: @kennethgillen @manics @sbesson @jburel

List playbooks in README

---

nightshade-webclients.yml
ome-demoserver.yml
ome-dundeeomero.yml
training-server.yml

Updated all playbooks together.
cc: @pwalczysko @kennethgillen

Bump OMERO version to 5.4.2

---

.gitignore
nightshade-webclients.yml
ome-dundeeomero.yml

Version bumps and JDK installation.

Nightshade 5.3.4 upgrades

---

ome-demoserver.yml

Install of test 5.4.3 on ome-demoserver.

(demoserver) Bump version, add JDK

---

www/tests/check_redirects.py
www/www-deploy.yml
www/www-jekyll.yml

Adds redirects needed by https://github.com/openmicroscopy/www.openmicroscopy.org/pull/195

Add OMERO features redirects for new navigation

---

.travis.yml
k8s-pg/playbook.yml
k8s/README.md
k8s/bootstrap/playbook.yml
k8s/postgres/molecule.yml
k8s/postgres/playbook.yml
k8s/postgres/tests/test_default.py
k8s/prerequisites/playbook.yml
requirements.yml

Building on https://github.com/openmicroscopy/prod-playbooks/pull/39 referencing org's tag rather than personal branch.

Ome k8s lochy

---

www/tests/check_redirects.py
www/www-deploy.yml

Adds redirect for content added to new website on https://github.com/openmicroscopy/www.openmicroscopy.org/pull/205
cc @sbesson

Add artwork redirect for logos

---

requirements.yml

Adds bugfix https://github.com/openmicroscopy/ansible-role-network/pull/3

Bump network role

---

nightshade-webclients.yml
ome-demoserver.yml
ome-dundeeomero.yml

Bump version to 5.4.5

---

release/presentations.yml

Add new playbook to update public OME presentations

---

omero/training-server/playbook.yml

This is a follow-up of the outreach updating PR, see https://github.com/openmicroscopy/prod-playbooks/pull/67#issuecomment-391861695
cc @jburel

Fix link not to point to jburel

---

omero/training-server/files/omero-web-outreach-webapps.omero
omero/training-server/playbook.yml
templates/omero-web-config-for-webapps.j2

Simple change for the outreach playbook.
Consulted with @kennethgillen

change password

---

omero/training-server/molecule.yml
omero/training-server/playbook.yml
omero/training-server/tests/test_default.py
site.yml

omero-monitoring-agents.yml is now part of the top-level site.yml
Also adds some basic tests for the outreach server.

outreach and monitoring top-level site.yml

---

omero/training-server/playbook.yml

This PR is trying to make use of the logic specified in [Simon's comment](https://github.com/openmicroscopy/prod-playbooks/pull/76#discussion_r195341856). 
Also, it fixes the typo in the override variable name. 
cc @joshmoore @manics @kennethgillen

Change pwd2

---

nightshade-webclients.yml
ome-demoserver.yml
omero/training-server/files/omero-web-outreach-webapps.omero
templates/omero-web-config-for-webapps.j2

Install of OMERO.parade on nightshade-webclients and the OME demo server.
Private config available at https://github.com/openmicroscopy/management_tools/pull/787/files

omero-parade install

---

omero/training-server/playbook.yml

See https://trello.com/c/6IwR4fMo/27-outreach-server-prep#comment-5b2d1eb0a2ad89fbf616ad95.
This PR is a pre-requisite for a future PR in MT, where the volumes to mount will be specified.
cc @sbesson

Add the nfs-mount role

---

release/group_vars/all.yml

Exposes another set of public images under http://downloads.openmicroscopy.org/images/

Public images

---

www/www-jekyll.yml

Also remove strange ``.`` at end sha256

Update version for OMERO 5.4.7

---

www/www-jekyll.yml

Bump version and sha256 version

Figure release announcement/ Upcoming workshop update

---

www/www-jekyll.yml

Includes the Bio-Formats 5.9.2 announcement

Deploy 2018.09.03 release of the OME website

---

www/www-jekyll.yml

Deploy 2018.09.06 release of the OME website

2018.09.06 release 

---

www/www-jekyll.yml

Bump website release for OMERO 5.4.8

---

www/www-jekyll.yml

Deploy 2018.10.02 website

---

nightshade-webclients.yml
ome-demoserver.yml
ome-dundeeomero.yml
requirements.yml
templates/nginx-omero.conf.j2
www/www-jekyll.yml

549 upgrades to prod OMERO plus new SSL deployment mechanism
Supporting (private) config at https://github.com/openmicroscopy/management_tools/pull/862

549 upgrades to prod OMERO plus new SSL deployment mechanism

---

www/www-jekyll.yml

Update website to version 2018.10.19
changes made to update www.o.org and ome-www.dev.o.org

Website update

---

www/www-jekyll.yml

cc @sbesson @manics @kennethgillen 
Could anyone deploy? I can't from Japan due to network issue. Thanks

Announce next workshop

---

www/www-jekyll.yml

Change made to update prod and staging hosts

website 2018.11.05

---

www/www-jekyll.yml

Add Fairsharing links to website for upcoming publication.

Update website with fairsharing links

---

www/www-jekyll.yml

Changes made to update staging and prod

upgrade website

---

omero/omero-monitoring-agents.yml
requirements.yml

Fixes https://trello.com/c/lLxHorjS/64-prom-exporter-unicodedecodeerror

Bump omero-prometheus-exporter role to 0.1.1

---

www/www-jekyll.yml

Deployed on staging and prod - see https://www.openmicroscopy.org/

Bump website version to 2019.02.26

---

omero/training-server/playbook.yml

Before the upcoming training, this PR is upgrading the versions of apps on outreach server.
cc @manics @jburel

Upgrade the versions of apps and omero

---

web-proxy/playbook.yml

See private configuration.
Not yet deployed.

Add openmicroscopy.ssl-certificate to web-proxies

---

legacy/ssl-deploy.yml

See https://github.com/openmicroscopy/management_tools/pull/932

legacy-ssl: use role vars

---

omero/omero-web-patch-settings.yml

This might be needed too? https://github.com/openmicroscopy/prod-playbooks/blob/96170aab24bd118b8f154c28c0919f0551e93102/omero/omero-web-patch-settings.yml#L16-L18

cyberessentials: omero-web-patch-settings.yml: SESSION_COOKIE_SECURE = True

---

www/www-jekyll.yml

changes made to update website
both staging and prod have been updated

website 2019.04.01

---

omero/training-server/playbook.yml

In prep for the Dundee training, upgrade the iviewer version on outreach.
cc @will-moore @jburel @sbesson @manics

Upgrade iviewer

---

www/www-jekyll.yml

Changes made to update prod and stating hosts

2019.04.11 update

---

www/www-jekyll.yml

Change made to deploy latest change on prod and staging

website 24.04.2019

---

www/www-jekyll.yml

Change made to update prod and staging hosts

update website 15.05

---

www/www-jekyll.yml

Bump website version for Bio-Formats 6.1.0

---

www/www-jekyll.yml

* bump date and sha256
prod and stating hosts have been updated with the changes
cc @sbesson

website 2019.06.13

---

ome-demoserver.yml

remove usage of webapp parameter
I ran it changes in check mode

demo webapps

---

nightshade-webclients.yml

* Remove usage of ``upgrade_webapps`` parameter
* Usage variables
```
PLAY RECAP *******************************************************************************************************************************************************************
ns-web.openmicroscopy.org  : ok=77   changed=6    unreachable=0    failed=0   
```

Nightshade web

---

ome-dundeeomero.yml

* remove duplicate mencoder installation
* install ice from wheel,
* do not install ice-devel 
in check mode
```
PLAY RECAP *******************************************************************************************************************************************************************
ome-dundeeomero.openmicroscopy.org : ok=75   changed=5    unreachable=0    failed=0   
```

nightshade playboook cleanup

---

omero/omero-firewall.yml

Further tightening of the firewall rules, and addition of a required `GPFS` port.

iptables: Restricting to correct vlan, and adding GPFS port.

---

www/www-static.yml

update website version
Updated staging and prod

website 2019.08.05

---

ome-demoserver.yml
requirements.yml

--depends-on https://github.com/ome/ansible-role-omero-web/pull/21

Test ome.omero_web role with SELinux

---

molecule/omero-training-server/molecule.yml

PSQL temporary fix rollback

---

www/www-static.yml

update date and sha256
Changes applied to prod and staging

Update website 2019.08.28

---

www/www-static.yml

website update 2019.08.29

---

omero/training-server/playbook.yml

In prep of the next week's training
cc @jburel @manics @joshmoore 
the playbook was successfully run against outreach, all worked fine.

Upgrade outreach OMERO and apps

---

www/www-static.yml

Update website with latest insight version
see https://github.com/ome/www.openmicroscopy.org/releases/tag/2019.09.03

bump version insight

---

nightshade-webclients.yml
ome-dundeeomero.yml

As the server is due some maintenance, upgrading the server, Web deployment and iviewer to the latest releases.

Bump OMERO.server, OMERO.web and OMERO.iviewer versions

---

requirements.yml

See https://github.com/ome/ansible-role-postgresql/pull/17
To be tested against the staging demo server

Consume PSQL role including the pyscopg2 patch

---

omero/training-server/playbook.yml

Upgrade in anticipation of the coming workshop. This was successfully run both against outreach and workshop servers.
cc @sbesson @manics @jburel

Upgrade figure

---

www/www-static.yml

Change applied to staging and prod

update website 2019.12.12

---

learning.yml
sls-gallery.yml

Gathers the various release-version values together from the Virtual Microscope and SLS Gallery playbooks, replacing any "latest" with the currently installed version.

Gather current release versions into global variables.

---

www/www-static.yml

deploy website 2019.12.19
prod and staging have been updated

 website 2019.12.19

---

learning.yml
omero/files/learning-omero-web.conf
omero/files/sls-gallery-omero-web.conf
sls-gallery.yml

Assumes the requirements updates from #225.

OMERO 5.6 for SLS Gallery and Virtual Microscope

---

omero/training-server/files/omero-web-outreach-webapps.omero
omero/training-server/playbook.yml

upgrade webtagging to 3.1.0 as per https://github.com/MicronOxford/webtagging/releases
cc @manics @jburel

Webtagging

---

omero/training-server/playbook.yml

to make the "workshop scripts" on outreach servers work.
successfully run against
ome-training-4
outreach
workshop
cc @jburel @manics

Upgrade training-scripts

---

www/www-static.yml

OMERO.server 5.6.1
OMERO.web 5.6.3

Bump website version to 2020.03.35 OMERO.server 5.6.1

---

nightshade-webclients.yml
ome-dundeeomero.yml

OMERO
- server 5.6.1
- web 5.6.3
- iviewer 0.9.1
- parade 0.2.1

Nightshade: bump OMERO server web iviewer parade

---

release/group_vars/all.yml

See https://github.com/ome/bioformats/pull/3528#issuecomment-600219568

Add public downloads folder for OBF file format

---

www/www-static.yml

Deploying the changes in anticipation of the OME 2020 Community meeting. cc @lunson .
The playbook was run successfully, both on 
``ome-www-dev`` and ``ome-www`` servers.
thanks @sbesson

Adjust playbook for release 4th April

---

requirements.yml
www/playbook.yml

This should allow additional AD groups to get access to this server

Add ome.sudoers to www playbook

---

www/www-static.yml

cc @joshmoore @sbesson 
A release of the www website.
The playbook was run successfully agains
ome-www-dev and
ome-www

Release of www 16April2020

---

www/www-static.yml

cc @sbesson 
This was successfully deployed on 
www-ome-dev
www-ome
servers.

Make changes to release www with ome2020 program

---

www/www-static.yml

Deployed successfully on 
1. ome-www-dev
2. www.open...py.org
cc @sbesson @dgault

www release corresponding to BF6.5.0

---

www/www-static.yml

Release of www 6 May 2020

---

www/www-static.yml

A new release again.
Deployed successfully on 
ome-www-dev
ome-www
cc @sbesson

deploy for www release 12May

---

www/www-static.yml

release 13 May, also includes the upgrade to insight 5.5.11
cc @sbesson 
successfully deployed on 
ome-www-dev
ome-www

release of www 13May

---

www/www-static.yml

bump date/version 15.05.2020
* update prod and staging
cc @pwalczysko

www release 15.05.2020

---

www/www-static.yml

cc @sbesson 
deployed successfully on
www-ome-dev
www-ome

Release of www 18May

---

www/www-static.yml

Sorry, forgot to open a PR on Tuesday
cc @sbesson 
All successfully deployed

Release of www 19May

---

www/www-static.yml

cc @sbesson 
deployed on
ome-www-dev
ome-www
successfully

release of www 21May

---

www/www-static.yml

cc @sbesson 
deployed on
ome-www-dev
ome-www
successfully

release www 22May

---

www/www-static.yml

cc @sbesson 
deployed on 
ome-www-dev
ome-www
successfully

Release www 23May

---

www/www-static.yml

cc @sbesson 
Deployed on
ome-www-dev
ome-www
successfully

Release www 24May

---

www/www-static.yml

@sbesson 
deployed on
ome-www-dev
ome-www

Release www 25May first

---

www/www-static.yml

@sbesson 
deployed on 
ome-www-dev
ome-www

Release www 26May first

---

ome-demoserver.yml
omero/training-server/playbook.yml

To be deployed at a good moment for their users.

Bump outreach and demo to OMERO.figure v4.3.0.

---

www/www-static.yml

cc @sbesson 
deployed on 
ome-www-dev
ome-www

Release of www 27May

---

www/www-static.yml

Website 2020.07.09

---

www/www-static.yml

Change required to update the website
prod and staging have both been updated

update version 2020.07.14

---

www/www-static.yml

Change applied to prod and staging

5.6.2 release

---

www/www-static.yml

website 2020.07.17

---

learning.yml

To be deployed Tuesday morning in concert with #273 for role upgrades.

Virtual Microscope upgrade

---

learning.yml
nightshade-webclients.yml
ome-demoserver.yml
ome-dundeeomero.yml
omero/training-server/playbook.yml
requirements.yml
sls-gallery.yml

- Builds on top of https://github.com/ome/prod-playbooks/pull/273
- Includes https://github.com/ome/prod-playbooks/pull/267
- Requires https://github.com/openmicroscopy/management_tools/pull/999

Nightshade upgrade 5.6.2 + web apps

---

ome-demoserver.yml

web 5.8.0
figure 4.3.2
iviewer 0.10.1

demo update OMERO.web and apps

---

nightshade-webclients.yml
ome-dundeeomero.yml

web 5.8.0
figure 4.3.2
iviewer 0.10.1

nightshade update OMERO.web and apps

---

www/www-static.yml

Deploy website with OMERO 5.6.3 release announcement.

---

www/www-static.yml

Deployed successfully on 
ome-www-dev
ome-www
cc @sbesson

Release of www 7 October

---

nightshade-webclients.yml
ome-dundeeomero.yml

nightshade: OMERO.server 5.6.3 OMERO.web 5.8.1

---

www/www-static.yml

Deployed on 
- ome-www-dev
- ome-www
All seems to have worked fine, the deployment looks good.
cc @sbesson @joshmoore

Release of www on 7 Dec 2020

---

omedev/playbook.yml
requirements.yml

New docker playbook for Docker development VMs
Requires https://github.com/ome/ansible-role-docker/pull/8

Add omedev-docker playbook

---

ome-demoserver.yml
templates/omero-web-config-signup.j2

A very tentative attempt to insert a long email text into the config of the demo server.
cc @manics @joshmoore 
see https://openmicroscopy.slack.com/archives/C0K5ME1EW/p1610560470190100?thread_ts=1610549673.183000&cid=C0K5ME1EW

Insert long email into config set

---

learning.yml
nightshade-webclients.yml
ome-demoserver.yml
sls-gallery.yml

Changes made and ran against
* pub-omero
* demo
* sls-gallery
* nightshade and nightshade-public
* learning (later today)

upgrade web and app

---

requirements.yml

Similar to https://github.com/IDR/deployment/pull/330

Bump ome.sudoers and ome.cli_utils roles

---

nightshade-webclients.yml
ome-demoserver.yml

Upgrade omero-web
Ran against prod and staging hosts

bump omero web version

---

omero/training-server/playbook.yml

cc @sbesson 
successfully deployed on
outreach
workshop

Upgrade outreach servers

---

omero/training-server/playbook.yml

Deployed successfully on all 4 training servers
cc @sbesson

Upgrade outreach web to 5.12.0

---

ome-demoserver.yml

Replaces https://github.com/ome/prod-playbooks/pull/324

Install newly released omero-demo-cleanup plugin into the demo server

---

release/group_vars/all.yml

Adding the mapping for the new Leica XLEF public samples

Add public samples for Leica-XLEF

---

omero/training-server/playbook.yml

update link to script following migration
cc @pwalczysko

use new repo for scripts

---

omero/nightshade-webclients.yml

bump omero-web version

---

omero/ome-demoserver.yml

* Update demo and pub-omero
* Note the unrelated change for mencoder. We would need to review the strategy for movie making script (low priority)

Demo django

---

omero/learning.yml

Fixes #345
Currently scheduled for Wednesday June 22 10:00 GMT

Upgrade OMERO.server of SLS learning deployment to 5.6.4

---

molecule/resources/prepare-iproute.yml
omero/training-server/playbook.yml

cc @sbesson 
deployed on ome-training-3
possibly there will be some DB to use tomorrow ?
cc @khaledk2

add logic for nightly pg dumps

---

omero/ome-dundeeomero.yml

2 actions in this PR:
1. Upgrade ns to OMERO.server 5.6.5.
2. Add two scripts assisting the Figure moves between groups, cf.  https://github.com/ome/prod-playbooks/issues/351

Upgrade ns

---

omero/learning.yml
omero/nightshade-webclients.yml
omero/ome-demoserver.yml
omero/ome-dundeeomero.yml
omero/training-server/playbook.yml
requirements.yml

cc @jburel 
As discussed, upgrading 7 items.

Upgrade server, web and web apps

---

README.md
playbooks/ome-demoserver.yml

Bump iviewer 0.15.0

---

playbooks/ome-demoserver.yml

Bump omero-figure 7.2.0

---

playbooks/ome-demoserver.yml

Bump - patch release
Ooops - pushed the branch to ome instead of my own repo.

Bump omero-figure 7.2.1
