ome/prod-playbooks

- .travis.yml
- www/molecule-playbook.yml
- www/molecule.yml
- www/requirements.yml
- www/www-deploy.yml
- www/www-jekyll.yml
- www/www.yml
Follow-up to a brief discussion on docs deployment:
This moves the jekyll docs deployment into a separate playbook. This should make it easier in future to give limited sudo permissions for an automated user to update the docs without requiring full access to the server to run the whole www.yml playbook.
Also refactors the `www.yml` playbook so that steps which aren't dependent on hardware or LSC can be tested with molecule.yml on travis.
Note that this playbook is NOT idempotent:
- jekyll build is forcibly rebuilt (this is expected)
- Both `NGINX - Performance tuning` steps conflict with the configuration file managed by the nginx-proxy role.
----
A future refinement could be to refactor the jekyll-build role to optionally run without `sudo`, so the docs could be built be a dedicated …
> Move jekyll into a separate playbook

- .travis.yml
- ome-demoserver.yml
Bump version to 5.3.4, add docs for upgrade usage.
Switch to 'localhost' which helps when testing this playbook elsewhere, otherwise web interface points to live demo server.
> OME OMERO demo server 5.3.4 upgrade

- ome-demoserver.yml
OMERO and Web versions for demo sever prod playbook incremented for demo server upgrade.
> Demo server: Bump versions for 540 upgrade.

- .travis.yml
See https://github.com/openmicroscopy/prod-playbooks/pull/11#issuecomment-347582513
This should increase the strictness of the demo playbook by failing Travis if the syntax is invalid.
> Remove ome-demoserver playbook from the allowed failures list

- ome-demoserver.yml
- requirements.yml
Upgrading ome-demoserver to OMERO 5.4.1
(Sibling PR: https://github.com/openmicroscopy/management_tools/pull/610/)
> ome demoserver to 5.4.1

- ome-demoserver.yml
- ome-dundeeomero.yml
Encouraged by @manics , I am adding the routine to for installing the Figure export script to the nightshade playbook (first commit) and the demo server playbook (second commit). The two added paragraphs are working fine already on the "outreach" server playbook, see https://github.com/pwalczysko/ansible-examples-omero/commit/5ece2affaed25c0432a4fd77ddd8e0aa37b040ba. 
To test, see that after you ran the playbooks, the figure pdf creation is enabled and works as expected.
cc @joshmoore @kennethgillen @manics
> Add routine for installing Figure_To_Pdf.py script

- nightshade-webclients.yml
Adding lvm tag to playbook, as done in ome-demoserver.yml at https://github.com/openmicroscopy/prod-playbooks/blob/master/ome-demoserver.yml#L27
This allows us to run only the storage part of the playbook when storage changes are required (potentially an on-line operation) without affecting the rest of the system.
> lvm tag for playbook (storage) run isolation

- www/tests/check_redirects.py
- www/www-deploy.yml
This updates the redirects for the About section of the old website so they all now point to the new website, except the Glencoe team page which I've redirected to their website (as suggested on https://trello.com/c/XkNLWbHP/606-remove-dom-from-www-legacy-etc)
> All About URLs linking to new website

- nightshade-webclients.yml
Downgraded Nightshade OMERO.web servers to 5.4.1.
Note: since the Server is at 5.4.2, you must set the following config on your OMERO.web instances to allow them to communicate with an older server.
`bin/omero config set omero.web.check_version false`
Part of https://github.com/openmicroscopy/management_tools/issues/642
Deployed on ns-web and ns-web-pub on 20180125
> Downgrade OMERO.web for NS to 5.4.1

- ome-dundeeomero.yml
Since the role no longer pulls in the `omero_server_datadir` defined in `host_vars`.
> Adding necessary managed repo config

- requirements.yml
- training-server.yml
@joshmoore encouraged me to 
1. move the new changes in ``ansible-examples-omero`` repo to this repo
2. work from now on from this repo rather than ``ansible-examples-omero``
The PR adds some os users needed for outreaches with facility managers who are supposed to ssh into the machine, to perform imports in-place as well as have an easy access to CLI in this way.
Also, it adds the docker install and the ldap installation in the docker.
> Get outreach in sync

- requirements.yml
- web-proxy/playbook.yml
- www/www-deploy.yml
- www/www-jekyll.yml
Follow-up of https://github.com/openmicroscopy/prod-playbooks/pull/28
- unifies the version of `nginx-proxy` to  1.7.0
- bumps the version of `jeykll-build` to 2.0.0 to fix the Travis build
- removes the post-task modifying the nginx worker processes as already handled via the `nginx_proxy_worker_processes` parameter
- removes the post-task modifying nginx worker connection to use the new `nginx_proxy_worker_connections` parameter introduced in 1.7.0
The `jekyll-build` bump should fix Travis which should pass for all playbooks.
In terms of deployment, the following playbooks should be tested with and without check-mode:
- ```$ ansible-playbook -i /path/to/ansible/inventory/prod-hosts --ask-become -C --diff playbooks/web-proxy/playbook.yml```
- ```$ ansible-playbook -i …
```
> Requirements unification and cleanup

- training-server.yml
This is a follow-up of https://github.com/openmicroscopy/prod-playbooks/pull/32.
Tried to run the trainin...yml playbook as described in https://github.com/openmicroscopy/prod-playbooks/pull/32#issuecomment-360505390.
This works, except that the password for ldap is either wrongly passed into [the config](https://github.com/openmicroscopy/prod-playbooks/pull/41/commits/e50167269e6aba6c15067cc718faf3e3f3db6dec#diff-dece4a429f875080d5d590525788c328R231) by me, or it does not work with salting, or both. When I hard-code the password for ldap 
``omero.ldap.password: "$HARDCODED_PWD" ``
then the whole playbook works as expected, even when run from the management repo.
I would not try fixing the password now without consulting @joshmoore , because he did have an opinion about how to do the …
> Get training in sync

- nightshade-webclients.yml
- ome-demoserver.yml
- ome-dundeeomero.yml
Refactors nightshade-webclients.yml ome-demoserver.yml ome-dundeeomero.yml to use a common set of optional variables for OMERO.figure.
> Use shared version vars for omero-figure

- www/tests/check_redirects.py
- www/www-deploy.yml
Previous implementation isn't working for https://www.openmicroscopy.org/site/support/ome-artwork/artwork-usage
> Fix artwork redirect

- www/tests/check_redirects.py
- www/www-deploy.yml
I thought this was already in place but it seems not.
Redirects the scripts page to the docs page which has been updated to more closely match the content.
This leaves only the minutes and meeting item of the community menu still going to the legacy URL
> Add redirect for script sharing page

- nightshade-webclients.yml
- ome-demoserver.yml
- ome-dundeeomero.yml
- requirements.yml
Prepare playbooks ahead of 5.4.4 release
cc @kennethgillen @manics
> User managed

- www/tests/check_redirects.py
- www/www-deploy.yml
Hoping this will default to redirecting any subpages missing back to legacy but if not, I guess I'll need to redirect all the meetings I've copied over individually instead until we agree what we're doing about the older stuff (see https://trello.com/c/7GTUHoJF/143-timeline-for-turning-off-legacy-and-redirecting-everything)
> Redirect /minutes/meetings to /events

- requirements.yml
- www/www-jekyll.yml
Ansible 2.4.3.0 has a known issue when git clone using HEAD as a version. See https://github.com/ansible/ansible/issues/30780 
This PR allows to deploy the OME website using Ansible 2.4 by bumping the `openmicroscopy.jekyll-build` role to version 1.3.1 which sets a default value to the Git branch.
> www: fix playbook execution with Ansible 2.4.3.0

- www/tests/check_redirects.py
- www/www-deploy.yml
Fix redirects for the errors in https://ci.openmicroscopy.org/view/Docs/job/OME-internal-merge-docs/1851/console and also add missing docs redirect from paper
> Fix redirects for docs subpages

- release/group_vars/all.yml
- release/permissions.yml
- release/public-images.yml
- release/release-acceptance.yml
This PR proposes the migrate some of the internal playbook used to manage our public resources (downloads, docs, public images) under the public prod-playbooks repository.
New playbooks added:
- `permissions.yml` checks the permissions of the top-level folder under downloads and docs
- `public-images.yml` manages the symlinks for our public images under http://downloads.openmicroscopy.org/images/
- `release-acceptance.yml` contains the FS operations operated during a release acceptance step to make downloads and docs folder public
Open questions:
- naming: I have grouped these playbooks a in a top-level `release` folder. A more representative names could potentially express the fact these are capturing the management of public static resources (artifacts, documentations, images...) e.g. …
> Public resources playbooks

- ome-dundeeomero.yml
- requirements.yml
Fixes the startup of OMERO on ome-dundeeomero which requires GPFS to be loaded and running before OMERO will properly start.
At the moment, a reboot of the server (normal during patching) will result in an OMERO instance running with an inaccessible OMERO.datadir
> Systemd dependency for ome-dundeeomero

- web-proxy/playbook.yml
Adding tags to allow `--skip-tags` when executing, e.g. a local test pipeline which will be adversely affected by such changes as storage and networking, which differ to the `prod` config.
See https://github.com/openmicroscopy/prod-playbooks/issues/24#issuecomment-381656949 for more rationale.
> Adding 'bootstrap' task tags for testing

- nightshade-webclients.yml
- ome-demoserver.yml
- ome-dundeeomero.yml
- requirements.yml
Production servers upgraded to latest OMERO version, and network role bumped for all of `prod-playbooks`.
> Bumping prod-playbooks NS & Demo to 5.4.6

- requirements.yml
- web-proxy/playbook.yml
This PR bumps requirements to a [development version of an ansible-role-nginx-proxy PR](https://github.com/openmicroscopy/ansible-role-nginx-proxy/pull/18) open to allow a deployed server like `web-proxy.openmicroscopy.org` to log the host header / domain name when using multiple `server` blocks.
When web-proxy/playbook.yml is run, this development version would be deployed to web-proxy.
> Use updated ansible-role-nginx-proxy in prod-playbooks

- omero/training-server/letsencrypt.yml
- omero/training-server/molecule.yml
- omero/training-server/playbook.yml
- Needed so that additional configuration can be added to the generated omero-web nginx config.
- Adds a letsencrypt playbook (automatically disabled in molecule since it requires a matching external DNS record and public http port).
> omero-web nginx nested includes and letsencrypt

- omero/training-server/files/omero-web-outreach-webapps.omero
- omero/training-server/playbook.yml
- templates/omero-web-config-for-webapps.j2
Commit https://github.com/openmicroscopy/prod-playbooks/commit/a5f728b13a0331d5f7030c54d7698fb9a8eb8ab1 from https://github.com/openmicroscopy/prod-playbooks/pull/67 added configuration for mapr and parade to the shared production omero config, however it should only be done on outreach. This PR reverts that commit and replaces it with a file that's only used by outreach.
This suggests we should run all playbooks in this repo with every PR to pick up inadvertent shared changes in future.
> Revert shared webapp mapr config

- omero/omero-firewall.yml
- omero/omero-monitoring-agents.yml
- omero/training-server/molecule.yml
- requirements.yml
- site.yml
Adds a playbook for configuring iptables on production OMERO servers. Currently deployed on pub-omero.openmicroscopy.org only since there's always a risk of locking yourself out when deploying firewall rules for the first time.
This is ready for review, but merging should wait until:
> Omero firewall (iptables)

- omero/omero-monitoring-agents.yml
Apply this playbook to the cross section of "omero(-web)" hosts and "monitored" hosts.
> monitoring: use ansible patterns for '&monitored'

- omero/omero-firewall.yml
- requirements.yml
Changes `iptables_raw` tasks to `iptables_raw_25`.
- https://github.com/openmicroscopy/prod-playbooks/pull/78#issuecomment-398460434
- https://github.com/openmicroscopy/ansible-role-iptables-raw/pull/1
> Bump iptables-raw to renamed module

- nightshade-webclients.yml
- ome-dundeeomero.yml
- omero/omero-monitoring-agents.yml
- templates/nginx-omero.conf.j2
- The equivalent of https://github.com/openmicroscopy/prod-playbooks/pull/73 (nginx omero-web.conf nested includes) for nightshade server and webclients.
- Install prometheus agents on nightshade server and web
> Nightshade server and web prometheus exporters

- omero/files/confd-nested-proxy-exporters-noweb.conf
- omero/files/confd-nested-proxy-exporters-web.conf
- omero/files/confd-nested-proxy-exporters.conf
- omero/omero-monitoring-agents.yml
- omero/training-server/molecule.yml
- web-proxy/molecule.yml
- web-proxy/playbook.yml
Nightshade's omero-web.conf proxies another server, so the omero web django prometheus exporter doesn't exist on nightshade.
The alternative to using `prod-omero-web` and `prod-omero:!prod-omero-web` would be a new group `(prod-)omero-server`
Updated: As discussed in Slack:
- `prod-omero` has been renamed `omero-server`
-  all `prod-` prefixes have been removed
> Nightshade requires a special nginx proxy exporters config

- ome-demoserver.yml
cc @manics @kennethgillen 
this temporary change is necessary for testing of RC2 see [lines 3 and 5](https://docs.google.com/spreadsheets/d/1BMbK1LNxP47ONT7Hj4bCGpY0Soo008jzLVP0_4ZlUTw/edit#gid=774711703).
The playbook should be re-run only against pub-omero which is used for the RC2 testing.
The change for the demo server will be done in another PR later on.
> Pwd required false and email config for web

- nightshade-webclients.yml
- ome-demoserver.yml
- ome-dundeeomero.yml
Prod OMERO server version bump.
Generated with `perl -pi.bak -e 's/5\.4\.6/5.4.7/g;' ome-*.yml nightshade-webclients.yml`
> 5.4.6->5.4.7 Version bump

- requirements.yml
This is a required bug-fix for OMERO.web servers using https://github.com/openmicroscopy/ansible-role-omero-web-django-prometheus, and fixes a race condition where an upgraded omero-web may be run before the temporary prometheus stats dir exists.
This fix should be applied before upgrading OMERO.web (run playbook `omero/omero-monitoring-agents.yml`), otherwise OMERO.web may fail to start after the upgrade.
> Update to dev django-prometheus role

- www/www-jekyll.yml
Deployed at https://www.openmicroscopy.org/2018/08/14/bio-formats-5-9-1.html
> Bump website version for Bio-Formats 5.9.1 release

- k8s/postgres/molecule-playbook.yml
- k8s/postgres/molecule.yml
- k8s/postgres/playbook.yml
- requirements.yml
Setup a daily backup of the k8s external postgres server
> ome-k8s-pg-01 backup

- release/group_vars/all.yml
See https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8535#p19716
This should publicize the LEO sample files under `curated/leo/public`
> Create top-level folder for public LEO sample files

- omero/training-server/playbook.yml
- templates/omero-web-config-for-webapps.j2
This PR should prep the outreach for the Basel MIAP.
First steps are
- upgrade to 5.4.7
- add config steps to iviewer so that Dataset and Well can be opened with ``Open with`` in iviewer
Note that the latter change changes the config for several servers, as there is a shared config file. But I propose this is a harmless, even beneficial change.
cc @jburel @joshmoore @manics
> New outreach changes

- ansible.cfg
In theory this repository can be used standalone without our private config. In practice it is assumed the roles are all in a common directory. This PR therefore adds a minimal ansible.cfg file to control the roles directory (`vendor/`)
> Add minimal ansible.cfg so repo can be run standalone

- omero/training-server/playbook.yml
- requirements.yml
Further prep of the outreach server
- restructure server script directories (consulted with @will-moore and @jburel, see screenshots below)
- install matplotlib for the FRAP script
- do not try to chown omero dir as we have now nfs read-only mounted bits in it (in place imports from mounted idr)
- bump omero web role, consulted with @manics 
Note: here, the content of ``workshop_scripts`` is shown
> Outreach prep continued

- ome-demoserver.yml
- ome-dundeeomero.yml
- requirements.yml
This is a major bump due to the role due to the change in behaviour (upgrade is automatically determined by comparing requested and installed versions), but in practice should just work since omero-web versions are hard-coded.
Note this was already the case for omero-server, but the comments in some of the playbooks were out of date.
> Bump omero web role

- nightshade-webclients.yml
- ome-demoserver.yml
- ome-dundeeomero.yml
Dundee production OMERO server upgrades to 5.4.8
Including:
* version bump for production servers
> Production OMERO server 5.4.8 upgrades

- omero/training-server/letsencrypt.yml
Fixes a bug discovered whilst renewing the outreach certificate with @pwalczysko - the certificate was correctly updated but Nginx wasn't restarted.
This also changes the renewal period to 30 days remaining as recommended by Lets Encrypt (default for the Ansible module is 10 days)
Note: work is ongoing to see whether certbot can replace this https://trello.com/c/TbZkQFhv/5147-replace-outreach-ansible-letsencrypt-with-certbot
> Letsencrypt reload after update

- www/www-jekyll.yml
Production server changes associated with the OMERO 5.4.9 release
- deploy the `2018.10.09` tag of the website containing the announcement and downloads page
- bump the version of the production OMERO server in Dundee to 5.4.9
> OMERO 5.4.9 release: website updates

- nightshade-webclients.yml
- ome-demoserver.yml
This has been an outstanding TODO for a while.
It was applied to OMERO.server, but OMERO.web was missed.
> Bump OMERO.web systemd number of files

- legacy/ssl-deploy.yml
A playbook to deploy SSL certs to legacy hosts.
Supporting MT configuration, including an inventory update at: https://github.com/openmicroscopy/management_tools/pull/864
> SSL update for legacy hosts.

- bootstrap/playbook.yml
- requirements.yml
- site.yml
Upgrade all distro packages in omedev bootstrap playbook.
Also adds an idempotence fix when resizing the root logical volume to fill the remaining space.
This should be safe to run on existing `omedev` group servers (currently only outreach/training servers) that you wish to upgrade
> Update omedev bootstrap playbook

- omero/training-server/playbook.yml
Supersedes https://github.com/openmicroscopy/prod-playbooks/pull/122
First change is motivated by the necessity to increaase the number of users on outreach to 50 - there are 48 participants already booked on one of the courses in December.
cc @jburel @joshmoore @manics
> Upgrade outreach2

- omero/training-server/playbook.yml
cc @sbesson @mtbc 
This addresses the problem of two concurrent imports under the same user  failing if they try to create one of the following folders under the ManagedRepository at the same time:
See https://github.com/IDR/idr0021-lawo-pericentriolarmaterial/pull/3#issuecomment-447126321 - this PR is going for the second suggested solution (by @sbesson ) because it is more robust solution I think.
I suppose there will be no detrimental effects coming from the fact that some data on the server were imported with the old config setup, whilst some (new, incoming) data will be imported using the path config in this PR ?
> Add config to enable parallel imports reliably

- omero/training-server/playbook.yml
- omero/training-server/tests/test_default.py
This should resolve https://trello.com/c/afkxY2IF/72-ldap-on-outreach, though we won't know for sure until it's deployed and tested.
Steps to deploy this (@pwalczysko, at your convenience):
1. Delete all existing docker containers. This is required because manual changes were made so it's not possible to guarantee there will be no conflicts when Ansible runs.
2. Deploy the full outreach playbook
3. Test the ldap server is accessible on localhost (the added molecule test in this PR passes so it should)
3. Reboot and verify LDAP still works as expected.
> outreach: replace docker iptables with manual iptables config

- omero/training-server/playbook.yml
bump the version of apacheds docker, as found during testing of https://github.com/openmicroscopy/prod-playbooks/pull/130 - the recent version is crucial for correct functionality
cc @joshmoore @manics
> Bump the apacheds docker version for ldap

- omero/training-server/letsencrypt.yml
the outreach playbook fails when letsencrypt cert is due and the playbook is run in ``--check`` mode. This PR just adds a comment about this (the remedy is simply to rerun the playbook in "wet" mode)
cc @manics @joshmoore
> Add comment about letsencrypt in check mode

- release/group_vars/all.yml
- release/public-images.yml
- Separate the formats using a standard layout with a public subfolder from the non-standard formats/images for clarity
> Bio-Formats 6: public images

- www/www-jekyll.yml
Version 2019.01.24 includes the announcement for the OMERO 5.4.10 release
> Bump version of OME website

- release/group_vars/all.yml
Another format with public data that was forgotten in #137.
Note one of official OME-TIFF samples with sub-resolutions, representative of pyramidal EM data, was derived from the public EMPIAR Gatan file.
> Add Gatan public folder

- www/www-jekyll.yml
Version of the website deployed for the [Bio-Formats 6.0.0](https://www.openmicroscopy.org/2019/02/18/bio-formats-6-0-0.html) announcement
> Update live version of the website

- requirements.yml
- www/www-deploy.yml
The role reverts the breaking log format change, so this is now defined as a parameter.
- See https://github.com/openmicroscopy/ansible-role-nginx-proxy/pull/21
> Nginx proxy role bump (www)

- www/www-jekyll.yml
This has been deployed onto https://www.openmicroscopy.org/
> Bump version of the website to 2019.03.14

- ome-demoserver.yml
- omero/omero-web-patch-settings.yml
- requirements.yml
- templates/nginx-confdnestedincludes-ssl-conf.j2
- templates/nightly-pg_dump-omero.sh.j2
Update Nginx to 1.14.2
Update SSL settings including HSTS
Update OMERO.web cookie and related settings
Update the playbook to use the postgresql ansible role 3 (changes default timezone from `GB` to `UTC`
Since this includes a minor refactoring you must delete `/etc/nginx/conf.d/omero-web.conf` to force it to be regenerated. See https://github.com/openmicroscopy/prod-playbooks/commit/02b7d94349d80dbbcbe16356d0d382aad2413958
SSL protocols and ciphers can be verified using https://nmap.org/nsedoc/scripts/ssl-enum-ciphers.html
`nmap -sV --script ssl-enum-ciphers.nse -p 443 HOSTNAME`
> Demo cyberessentials

- www/www-deploy.yml
This removes the assumption that the default values are used, allowing private variables to override if wanted
> Couple NGINX SSL certificate to ssl-certificate variable

- ome-demoserver.yml
Use the role default `/etc/ssl/localcerts/` for all certs.
> demoservers: use default ssl_certificate paths from role

- nightshade-webclients.yml
- ome-dundeeomero.yml
- omero/omero-web-patch-settings.yml
- templates/nginx-confdnestedincludes-ns-pub-redirects-conf.j2
- templates/nginx-omero.conf.j2
Similar to the changes made on demo: https://github.com/openmicroscopy/prod-playbooks/pull/145
- Update Nginx to 1.14.2
- Update SSL settings including HSTS
- Update OMERO.web cookie and related settings
- In addition adds the `/pub/schleicher-et-al-2017` → `/webclient/?show=project-27936` redirect on both servers
Since this includes a minor refactoring you must delete `/etc/nginx/conf.d/omero-web.conf` on `ns-webclients` to force it to be regenerated:
Note there are three Nginx servers and two OMERO.web servers:
- ns-web (internal read-write OMERO.web + Nginx)
- ns-web-pub (omero.lifesci, public read-only OMERO.web + Nginx)
- nightshade (Nginx only, proxied to ns-web)
> Nightshade and nswebclients cyberessentials

- omero/omero-web-patch-settings.yml
Deployed to get web-apps working again, this will need further investigation
Original change: https://github.com/openmicroscopy/prod-playbooks/pull/145/files#diff-21abe72460789362123693324f67520d
> Disable CSRF_COOKIE_HTTPONLY, breaks several OMERO.web apps

- .travis.yml
See https://github.com/openmicroscopy/prod-playbooks/pull/159#issuecomment-485848708
`ome-ansible-molecule-dependencies` is shipping Ansible 2.4 which requires Python 2.7
> Set Python to 2.7 in .travis.yml

- templates/nginx-confdnestedincludes-ns-pub-redirects-conf.j2
Adding a redirect for the new publication group on nightshade.
cc @sbesson
> Add redirect for new link to publication on nightshade pub

- .travis.yml
- jupyterhub/molecule.yml
- jupyterhub/playbook.yml
- jupyterhub/tests/test_default.py
- requirements.yml
- site.yml
https://trello.com/c/o9dexcGQ/23-fallback-jupyterhub-server
Since we're relying on JupyterHub for critical parts of a training session we should have a backup server in case there's an outage on idr-analysis/training
- This installs the upstream Docker CE package on RHEL. This is not officially supported by Docker, only the Enterprise Edition is.
- The default Docker iptables/forwarding is disabled so we can restrict all outgoing connections from Docker containers (Jupyter notebook servers). This is important since there is no authentication on JupyterHub, but adds to the complexity of the playbook.
> jupyterhub-training-alt fallback server

- omero/training-server/playbook.yml
- requirements.yml
Discussed with @sbesson : Git installation on outreach is of advantage to be able to manage the versions of the training scripts there (maintenance mainly) .
Second goal here is to be able to clone idr repos and thus use the bulk.yml and tsv files from there easily.
@jburel @manics @joshmoore
> Install git on outreach

- www/www-deploy.yml
Since our logos are all uppercase, placing "openmicroscopy.org" in
front of them might encourage someone to go, for example,
openmicroscopy.org/OMERO which currently is 404.
This has been run on ome-www-dev with:
```
ansible-playbook -i ../ansible/inventory/staging-hosts  playbooks/www/www-deploy.yml --ask-become
```
Test with:
* https://ome-www-dev.openmicroscopy.org/OMERO/
* https://ome-www-dev.openmicroscopy.org/BIO-FORMATS/downloads
* etc.
> aliases: handle uppercase product names

- molecule/www/tests/test_redirects.py
- www/www-deploy.yml
For discussion: Now that /support explicitly lists tags (https://github.com/ome/www.openmicroscopy.org/pull/298), perhaps the overall link can go to the new category?
> Propose new forums location: data-management

- omero/training-server/playbook.yml
remove duplicate
Installation already covered by 
```
- name: OMERO.figure server-side prerequisites, script prerequisites + web server for decoupled OMERO.web
become: yes
yum:
name: "{{ item }}"
state: present
with_items:
- python-reportlab # For OMERO.figure
- python-markdown # For OMERO.figure
- mencoder # For the 'make movie' script
- scipy
- python-matplotlib # For "simple frap with figure" script
```
> mencoder cleanup

- omero/training-server/playbook.yml
- requirements.yml
* Update outreach to 5.5
* use the new role to install zsh 
cc @pwalczysko @dominikl 
```
TASK [ome.cli_utils : system packages | cli user utils] **********************************************************************************************************************
changed: [outreach.openmicroscopy.org] => (item=[u'bzip2', u'screen', u'tmux', u'zsh'])
PLAY RECAP *******************************************************************************************************************************************************************
outreach.openmicroscopy.org : ok=152  changed=26   unreachable=0    failed=0   
```
> Outreach update55

- .travis.yml
- molecule/release/Dockerfile.j2
- molecule/release/molecule.yml
- molecule/release/prepare.yml
- molecule/release/tests/test_default.py
- release/release-acceptance.yml
This PR proposes to improve the discoverability and maintenance of latest, major and minor versioned URLs for downloads and documentation components via the Ansible release playbook rather than Apache redirects at the moment.
This changeset primarily affects the `release-acceptance.yml` playbooks:
- refactor the release folder checks and fail the playbook if either variables are undefined or release folders are missing
- add tasks creating symlinks `x.y`, `x` and `latest` linking the to specified `x.y.z` version for both documentation and downloads unless the version is a pre-release one e.g. 5.5.0-rc1 e.g.
Molecule tests have been added to cover the various tasks achieved by the playbook i.e. `.htaccess` removal, chowning/chmoding and symlink creation both in the case of pre-releases as …
> Versioned URL variants

- .travis.yml
- molecule/release/Dockerfile.j2
- molecule/release/molecule.yml
- molecule/release/prepare.yml
- molecule/release/tests/test_default.py
- release/release-acceptance.yml
In preparation of upcoming proposals to the release playbook, this creates a molecule scenario testing the outcome of the `release-acceptance.yml` playbook (`.htacces` removal + ownership/permissions)
> Add molecule tests for release playbooks

- omero/training-server/playbook.yml
See discussion https://openmicroscopy.slack.com/archives/C1PJHN2D7/p1561048398043900 - the aim here is to have the metadata plugin installed on the outreach machine so that the server can see it. The next step, as described in Slack, will be to test and implement the UI-based server side script in Import scripts > populate metadata to harvest this cli code and thus enable users to easily create tables from csv files, without using elaborate Fiji, R or other scripts/coding.
cc @jburel @will-moore
> Install omero-metadata plugin

- k8s/postgres/playbook.yml
- molecule/omero-training-server/molecule.yml
- ome-demoserver.yml
- omero/training-server/playbook.yml
- requirements.yml
Workaround https://forum.image.sc/t/fyi-not-possible-to-create-new-omero-instance-with-latest-postgresql-versions/26929
- Changes `openmicroscopy.postgresql-3` to `ome.postgresql` (existing `openmicroscopy.postgresql` is unchanged)
- Pins the pg version to `9.6.13` in the training-server molecule test. This is the only playbook that has a full OMERO molecule test.
Not yet tested
> Postgres new omero db molecule workaround

- templates/omero-web-config-for-webapps.j2
The default web viewer in templates/omero-web-config-for-webapps.j2 can be overridden on a case-by-case basis
> NSweb default iviewer can be overridden

- molecule/release/prepare.yml
- molecule/release/tests/test_default.py
- release/release-acceptance.yml
Follow-up of #177. A main issue associated with the new URLs aliases (latest, minor, major) associated with every release is the absence of redirection to the canonical version URL. A typical usage is consumers relying this redirection to programmatically retrieve the latest version of a component.
This PR updates the logic for creating these aliases and creates `{latest,minor,major}/.htaccess` files redirecting to the canonical versioned URLs rather than symlinks transparently served by the Web server.
As previously, an (UoD internal-only) test of this PR has been created under http://downloads.openmicroscopy.org/omero-test/:
- the 5.4 alias has been created using the previous iteration and should serve the 5.4 content but not redirect
- the 5.5, 5 and latest aliases have been created by …
> Versioned URLs - part 2

- jupyterhub/playbook.yml
- molecule/omero-training-server/molecule.yml
- nightshade-webclients.yml
- ome-demoserver.yml
- ome-dundeeomero.yml
- omero/omero-monitoring-agents.yml
- omero/omero-web-patch-settings.yml
- omero/training-server/playbook.yml
- requirements.yml
- site.yml
- web-proxy/playbook.yml
- www/www-deploy.yml
See also https://github.com/ome/ansible-example-omero-onenode/pull/1 and https://github.com/IDR/deployment/pull/194
Switch all roles associated with the installation of OMERO.server and OMERO.web to use the roles published under the Galaxy `ome` namespace (following the deprecation of the `openmicroscopy` namespace).
Most roles are bumped to the next patch release which should be harmless. Only exceptions are `ome.ice 2.1.1 -> 3.0.0` (drop support for Ice 3.5) and `ome.omero_python_deps 1.1.0 -> 2.0.1` (remove Scipy)
To be run in check-mode against:
```
(ansible) sbesson@ls30630:prod (master) $ ansible-playbook -KC playbooks/ome-dundeeomero.yml 
...
PLAY RECAP *********************************************************************************************************************************** …
```
> Ansible OMERO Galaxy roles: switch to new namespace

- release/group_vars/all.yml
All these formats have sample files which can be made public immediately. Post-deployment, the new folders will be available under https://downloads.openmicroscopy.org/images/ and can be cross-linked from the Bio-Formats documentation.
> Publicize more imaging file format samples

- www/www-static.yml
There was a missing `,` between `#jumpbox~p .headerspace~h3` in https://github.com/ome/prod-playbooks/pull/188 which meant the online users section of the footer wasn't fully hidden.
Deployed to ome-www-dev
> www phpbbforum: fix typo in style (missing ,)

- ome-demoserver.yml
This is in preparation for the OMERO 5.5.1 release and has been manually performed on pub-omero. A decision needs to be made if we're happy with it in general for the demo servers.
Looking at the diff, I think we're approaching needing a simpler way to do this, e.g.
```
pip install omero-plugins==x.y.z
```
cc: @pwalczysko @sbesson @manics
> Add pip install to demo playbook

- molecule/omero-training-server/tests/test_default.py
- omero/training-server/playbook.yml
When writing the g.doc about DropBox, I realized that we have quite a few redundant users and DropBox folders on outreach.
This PR is removing the corresponding bits from the playbook.
Also, I will remove manually the already existing DropBox folders on outreach.
This includes a "falso" ``/OMERO/DropBox`` folder, which should have never existed.
cc @jburel @joshmoore @manics @sbesson 
Edit 
Removed the redundant folder from Outreach server as indicated in the header. Dropbox on outreach still works.
> Remove fm users and their dropbox folders

- omero/training-server/playbook.yml
the dedicated Workshop scripts subfolder contains a duplication of the two scripts, Kymograph and Kymograph analysis. This was because the mainline scripts of the same names were not working properly.
Now, we have the mainline scripts released (checked that they work properly on outreach).
Thus, removing the duplicates in the Workshop scripts folder from the playbook.
The playbook was run successfully for outreach server. 
cc @sbesson @manics @will-moore
> Remove Kymo and Kymo Analysis from workshop folder

- jupyterhub/playbook.yml
- legacy/ssl-deploy.yml
- nightshade-webclients.yml
- ome-demoserver.yml
- ome-dundeeomero.yml
- requirements.yml
- web-proxy/playbook.yml
- www/www-deploy.yml
- switches from the deprecated `openmicroscopy.ssl-certificate` to `ome.ssl_certificate`
- updates playbooks to consume the new role
- defines handlers reloading the nginx server when the SSL certificate has changed
> Use ome.ssl_certificate role

- ome-demoserver.yml
- templates/nginx-confd-websockets-conf.j2
- templates/nginx-confdnestedincludes-omerows-conf.j2
Closes https://github.com/ome/prod-playbooks/issues/198
Deployed to pub-omero. To test connect to `wss://pub-omero.openmicroscopy.org/omero-ws`, for example using:
- https://github.com/ome/omero-py/pull/18
- https://github.com/ome/omero-insight/pull/66
This enables:
- ~~Direct `wss://host:4066` connections to OMERO using a self signed certificate~~ blocked by the firewall
- `wss://host:443/omero-ws` connections to OMERO via Nginx (port `443` is the default wss port in OMERO.py and soon the [Java Gateway](https://github.com/ome/omero-gateway-java/pull/21) so can be omitted
> Support wss external websocket connections to demo

- bootstrap/playbook.yml
- jupyterhub/playbook.yml
- k8s/bootstrap/playbook.yml
- k8s/postgres/playbook.yml
- k8s/prerequisites/playbook.yml
- nightshade-webclients.yml
- ome-demoserver.yml
- ome-dundeeomero.yml
- omero/omero-firewall.yml
- omero/omero-monitoring-agents.yml
- omero/training-server/playbook.yml
- requirements.yml
- web-proxy/playbook.yml
- www/playbook.yml
This should complete the review and the update of this playbook repository to drop the usage of the deprecated Galaxy [openmicroscopy](https://galaxy.ansible.com/openmicroscopy/) roles in favor of the new [ome](https://galaxy.ansible.com/ome/) ones.
The changes in `requirements.yml` should mainly consist of patch version increments of the Galaxy roles as per the migration. Two exceptions:
- `ome.nfs_mount`: `1.0.0` -> `1.2.1` (Ubuntu support, passno parameter, nfs version support, CI & molecule2)
- `openmicroscopy.postgresql 2.0.0` is fully superseded by `ome.postgresql`
- the `ome-dundeeomero` playbook is upgraded to consume `ome.postgresql`
> Review requirements.yml and use new OME Galaxy roles across the board

- omero/training-server/playbook.yml
This is in preparation of the Munich workshop (next week)
Upgrading among others iviewer and training-scripts (new release to fix "simple frap" script there).
The changes are pertaining only to ``outreach`` server. The ``workshop`` server is its mirror, nevertheless, after consultation with @manics I was told that a tactics where both servers will be governed by a single playbook is being worked on. 
But, in the meantime, to avoid some conflicts, I am expected to prep the playbook changes as I did up till now (and for ``outreach`` only).
cc @manics @sbesson @jburel @dominikl 
The playbook was successfully run against ``outreach`` and all is fine.
> Upgrade apps and training-scripts versions

- release/group_vars/all.yml
As discussed with @ome/formats, the internal name of the public folders has been changed to `public` to match the other formats.
This playbook has been deployed so that https://downloads.openmicroscopy.org/images/OME-TIFF/ and https://downloads.openmicroscopy.org/images/OME-XML/ keep working.
Proposing to merge as soon once Travis is green.
> Update public image folders to consume new public OME-TIFF/OME-XML folders

- learning.yml
- requirements.yml
- sls-gallery.yml
For both Virtual Microscope and SLS Gallery,
- Removes use of `mtbc.*` roles. (https://github.com/openmicroscopy/management_tools/pull/1113 covers the remaining TLS certificate configuration.)
Fixes #216. Other improvements will follow in subsequent PRs once this is merged.
> fix outstanding playbook issues

- learning.yml
OMERO.iviewer on https://learning.openmicroscopy.org/ is still back on v0.7.1. This PR ensures that when the playbook is run for the next scheduled maintenance of Virtual Microscope OMERO.iviewer will be upgraded to the latest stable version.
> Force upgrade of OMERO.iviewer on Virtual Microscope.

- learning.yml
- sls-gallery.yml
Adds space for OMERO.server and OMERO.web to live separately on `/opt/omero/`. Should already pass for SLS Gallery but will fail on Virtual Microscope until existing data is migrated during the maintenance window.
> separate /opt/omero/ mount on learning and sls-repo

- learning.yml
- sls-gallery.yml
Both `learning.yml` and `sls-gallery.yml` include,
```
omero_server_systemd_start: False
omero_web_systemd_start: False
omero_web_setup_nginx: False
```
It wasn't clear to me that this also prevents the services from being enabled at all. This extra task fixes that issue. The services are already otherwise enabled on the actual server but this PR reflects that.
> start services on boot: learning, sls-repo

- learning.yml
- sls-gallery.yml
The Virtual Microscope and SLS Gallery servers have finite space for `/opt/omero/` and OMERO.server logs are so large and compressible that it seems well worth saving that space so this PR adjusts the Logback configuration to compress log files on rollover.
This has already been run on SLS Gallery. For Virtual Microscope we'll wait for the next maintenance window such as when 5.6.1 is released.
At a quieter time we should look at where we can roll the functionality of these various tasks into existing or new roles.
> Compress OMERO.server logs for learning and sls-repo.

- omero/training-server/playbook.yml
After discussion with @jburel and @manics , this is motivated by the need to have a websocket connection to outreach servers for the next outreach session, to be able to use MyBinder.
This PR basically leans on https://github.com/ome/prod-playbooks/pull/204, trying to make similar changes for the outreach playbook as were done in https://github.com/ome/prod-playbooks/pull/204 for demo server.
> Add websocket connection motifs for outreach servers

- molecule/nightshade-webclients/Dockerfile.j2
- molecule/nightshade-webclients/molecule.yml
- molecule/nightshade-webclients/tests/test_default.py
- molecule/ome-dundeeomero/Dockerfile.j2
- molecule/ome-dundeeomero/molecule.yml
- molecule/ome-dundeeomero/tests/test_default.py
- nightshade-webclients.yml
- ome-dundeeomero.yml
- requirements.yml
- templates/nginx-omero.conf.j2
5.6.0 Nightshade upgrade.
Also adds some molecule tests. The verify step of the webclient test currently hangs on Travis but passes locally, so is disabled. Previously there were no tests at all for these playbooks so this is still an improvement.
> nightshade upgrade

- ome-demoserver.yml
This removes on of the idempotence errors by declaritively setting the extra nginx config isntead of patching it.
Already deployed on demo since it was being restarted anyway whilst investigating a problem (still not working though)
> Use omero.web.nginx_server_extra_config instead of patching generated config

- jupyterhub/playbook.yml
- molecule/jupyterhub/tests/test_default.py
- requirements.yml
Updates JupyterHub, see
Updates the notebook image to `openmicroscopy/training-notebooks:0.7.2`
> Update the training backup jupyterhub server

- omero/training-server/playbook.yml
These changes are deployed successfully on workshop, outreach and ome-training-4 servers. 
cc @manics @jburel
> Upgrade outreach servers for new apps

- ome-demoserver.yml
See https://forum.image.sc/t/error-when-exporting-pdf-from-omero-figure/35460
This should fix the install of reportlab on demo server. Uses the commands copied from https://github.com/ome/prod-playbooks/blob/5a9711b718233f3583811e3dfe4ce67a5fb28ee6/ome-dundeeomero.yml#L295
> demoserver_reportlab

- release/group_vars/all.yml
See also https://github.com/ome/bio-formats-documentation/pull/157
This should create a public folder under https://downloads.openmicroscopy.org/images/ for the public MetaXpress filesets in our curated QA repository /cc @melissalinkert
> Add public samples images for MetaXpress

- omero/training-server/playbook.yml
Upgrade of omero and omero-web
cc @sbesson @manics @jburel 
I have upgraded successfully 
- outreach
- workshop
- ome-training-4
I will wait with ome-training-3 upgrade until https://github.com/openmicroscopy/management_tools/pull/1180 is clarified.
> Upgrade training servers

- omero/training-server/playbook.yml
- templates/nginx-confdnestedincludes-omero-ms-zarr.j2
This starts the latest docker image for omero-ms-zarr from Docker Hub, listening on port 8080. This will allow us to point notebooks and similar at:
```https://workshop.o.org:8080/image/$ID.zarr```
Suggestions for similar other configuration welcome. It is unclear how many concurrent users this single endpoint will be able to handle.
cc: @pwalczysko @mtbc @will-moore @jburel @manics
> training-server: activate omero-ms-zarr

- learning.yml
- ome-demoserver.yml
- ome-dundeeomero.yml
- omero/training-server/playbook.yml
- requirements.yml
- sls-gallery.yml
Prepares the upgrade of the demo servers to the latest released OMERO components - see https://www.openmicroscopy.org/2020/07/16/omero-5-6-2.html
As discussed earlier with @mtbc @manics @will-moore, also includes an upgrade of the OMERO Ansible roles to their latest versions including the updates to the `ome.postgresql` variables across all production playbooks.
> Demo 5.6.2 upgrade

- sls-gallery.yml
Now deployed.
Curiously, had to restart omero-web manually for the upgraded version to be running.
> SLS Gallery upgrade.

- www/www-static.yml
Releasing the www with changes mainly relating to help.op..py.org 
cc @sbesson @jburel 
This works fine on
1.  ome-www-dev
2.  openm..py.org
> Release of www 11August

- web-proxy/playbook.yml
This version was managed privately previously. This PR migrates it to the public playbooks similarly to the other web deployments
> Add nginx_version to the public web-proxy playbook

- ome-demoserver.yml
- requirements.yml
As discussed this morning, this will manually require a dump of the DB, an installation + uninstallation of the current PSQL and a restore of the DB.
To be tested on `pub-omero` first
> Bump PostgreSQL version to 11 on OME demo server playbook

- omero/omero-firewall.yml
Changes the GPFS and check-mk source IPs to be configurable since they're useless to anyone outside who uses these playbooks as a reference.
> Omero firewall update

- requirements.yml
Closes https://github.com/ome/prod-playbooks/issues/281
The `omero/omero-monitoring-agents.yml` playbook has been run against `staging-hosts`
> ome.prometheus_postgres 0.4.0

- omero/training-server/playbook.yml
Upgrading omero and apps on the outreach server.
Successfully upgraded
- ome-training-4
- outreach
- workshop
cc @manics @sbesson 
ToDo" Upgrade ome-training-3 - but this needs to be done on top of https://github.com/openmicroscopy/management_tools/pull/1180, so will finish that one off tomorrow
> Upgrade server and apps on training servers

- molecule/ome-dundeeomero/tests/test_default.py
- ome-dundeeomero.yml
Proposed upgrade workflow (tested on `pub-omero`)
bash-4.2$ time pg_dump -j 4 -Fd -f /uod/idr/nightshade/backups/nightshade-20200922-      dump_omero.dir/ omero
real	5m57.268s
user	9m49.028s
sys	0m14.928s
[root@ome-dundeeomero nightshade]#  time tar -czvf /uod/idr/nightshade/nightshade-varlibpgsql-20200922.tar.gz /var/lib/pgsql/9.6/
...
real    43m48.535s
user    39m59.934s
sys     2m12.884s
> Bump ome-dundee PostgreSQL version to 11

- ome-demoserver.yml
Ready to deploy now OMERO 5.6.3 is released.
> Bump install release versions for demo servers.

- sls-gallery.yml
Ready to deploy now OMERO 5.6.3 is released.
> Bump install release versions for SLS Gallery.

- omero/training-server/playbook.yml
Upgrades
- OMERO to 5.6.3
- OMERO.web to 5.8.1
These changes were successfully deployed on following servers
- ome-training-3  and 4
- workshop
- outreach
cc @sbesson
> Upgrade outreach servers for OMERO 563

- omero/training-server/letsencrypt.yml
I noticed that the variable name at the end of the script has an underscore, while the actual variable that is checked in the script to conditionally run doesn't have an underscore. So, uncommenting the line at the end of the script and setting it to True doesn't actually do anything.
> fixes typo in variable name -  https_letsencrypt_enabled

- omero/training-server/playbook.yml
- templates/nginx-confdnestedincludes-minio-publicscratch.j2
Credentials are randomly generated on the first startup and are saved to `/etc/minio/docker-minio.env`
```
. /etc/minio/docker-minio.env
mc config host add localhost http://localhost:9000 "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
mc mb localhost/publicscratch
mc policy set download localhost/publicscratch
mc config host add test-server --insecure https://test-server <MINIO_ACCESS_KEY> <MINIO_SECRET_KEY>
```
> Add minio server

- www/files/deploy
- www/playbook.yml
- www/www-static.yml
Ports the script proposed and tested in https://github.com/ome/www.openmicroscopy.org/pull/426 to the Ansible playbook for updating the www server
This should remove the constant requirement to update the playbook variable as we release the website.
The script is installed under `/usr/local/bin/deploy` and should be executable as a standalone by anyone with sudo permissions.
> Replace ome.deploy_archive by deployment script to update the static website

- ome-demoserver.yml
- ome-dundeeomero.yml
- requirements.yml
- templates/nightly-pg_dump-omero.sh.j2
Recently we discovered the current pgdump directory format may lead to loss of the previous backup if an error occurs during the current backup.
This replaces the custom cron job with the [ome.postgresql_backup role](https://github.com/ome/ansible-role-postgresql-backup) as used in https://github.com/ome/prod-playbooks/blob/2afc0764391e467411745946b5577973d7fa5625/k8s/postgres/playbook.yml#L25-L28
Note this role dumps all databases
> Replace nightshade pg cronjob with ome.postgresql_backup

- requirements.yml
Following the publication of the role to https://galaxy.ansible.com/idr/redmine_tracker
> Use idr.redmine_tracker from Ansible Galaxy

- omero/training-server/playbook.yml
This allows to store the unencrypted password for `importer1` and leave the playbook do the encrypting. The usage of a determined salt allows the playbook to be idempotent
> Use password_hash filter with salt with user module

- ome-dundeeomero.yml
This mount point had been previously created to test some processing pipelines but has not been used.
After discussion with @graemeball, proposing to remove this from the deployment playbook. If this becomes useful again, we can come back to this effort.
> Remove NGOM mount point from ome-dundeeomero playbook

- omero/training-server/playbook.yml
Upgrading all training servers with
- OMERO.web 5.9.0
- OMERO.figure 4.4.0
- OMERO.iviewer 0.10.2
Run successfully on 
- outreach
- workshop
- ome-training-3
- ome-training-4
cc @sbesson @jburel 
Edit: Also the second upgrade to OMERO.web 5.9.1 was successfully done on all fourn training servers.
> Upgrade omero-web, figure and iviewer

- www/www-static.yml
Attempts to reduce the number of  steps required to update the OME website - see https://ome-contributing.readthedocs.io/en/latest/jekyll.html#id1
Rather than having to run a manual deployment command post tagging of the website, this installs a cron job which runs hourly and tries to update the website if a new version is installed. The deploy script can still be executed manually.
> Add cron job for auto-deploying the OME website

- learning.yml
- molecule/ome-dundeeomero/molecule.yml
- molecule/omero-training-server/molecule.yml
- ome-demoserver.yml
- ome-dundeeomero.yml
- omero/training-server/playbook.yml
- requirements.yml
- sls-gallery.yml
Brings most roles inline with the latest release versions
- ome.ice: [4.0.0 -> 4.3.0](https://github.com/ome/ansible-role-ice/compare/4.0.0...4.3.0): Ubuntu/CentOS8 support, `ice-runtime` cleanup
- ome.java: [2.0.3 -> 2.1.0](https://github.com/ome/ansible-role-java/compare/2.0.3...2.1.0): `java_version` variable
- ome.baseps: [1.1.0 -> 1.2.0](https://github.com/ome/ansible-role-basedeps/compare/1.1.0...1.2.0): `curl` 
- ome.iptables_raw: [0.2.1 -> 0.3.1](https://github.com/ome/ansible-role-iptables-raw/compare/0.2.1...0.3.0): additional checks (requires Ansible 2.6+)
- ome.omero_server: [3.3.0 -> 4.0.1](https://github.com/ome/ansible-role-omero-server/compare/3.3.0...1.2.0): (Python 2 dropped)
- ome.omero_user: [0.2.0 -> 0.3.0](https://github.com/ome/ansible-role-omero-user/compare/0.2.0.. …
> OMERO playbooks: upgrade roles and install certificates

- ome-dundeeomero.yml
Proposed changes for deployment
> SLS OMERO.server: playbook and concurrent import fixes

- learning.yml
- nightshade-webclients.yml
- ome-demoserver.yml
- omero/training-server/playbook.yml
- sls-gallery.yml
> Bump OMERO.web to 5.12.0 across all production UoD playbooks

- requirements.yml
Include `omero_prometheus_tools` bug fix as well as the cleanup of former Python 2-based deployment.
> Bump ome.omero_prometheus_exporter to 0.3.3

- requirements.yml
- www/www-deploy.yml
- www/www-static.yml
This was driven by the issue in the www/www-legacy proxying following the migration. As a general rule, this removes a non-necessary dependency.
Changes;
- removes the proxying of `/Schemas` as these are included as part of the static website artifact (see https://github.com/ome/www.openmicroscopy.org/pull/420)
- removes the proxying of `/XMLschemas`, replaced by a location redirect
- removes the proxying of `/Schemas/Documentation/Generated`, replaces by a similar strategy as the old phpbb forum i.e. downloading a static bundle containing the oXygen documentation and using `location/alias` to serve the documentation
- add redirects for legacy `/Schemas/Samples` endpoint
Also depends on https://github.com/ome/ansible-role-nginx-proxy/pull/33 to fix the broken deployment following recent …
> www: remove proxying of OME schemas

- omero/training-server/playbook.yml
cc @sbesson 
the changes are on top of https://github.com/ome/prod-playbooks/pull/334
Deployed successfully on ome-training-3
Possibly there is a change in ``mapr`` in between ?
This here is a status from couple of days ago, with RC on mapr.
> Django upgrade

- omero/learning.yml
Fixes #339 
To be deployed on Thursday April 7th
> learning: bump OMERO.web components to the released versions using Django 3.2

- omero/learning.yml
- omero/nightshade-webclients.yml
- omero/ome-demoserver.yml
- omero/sls-gallery.yml
- omero/training-server/playbook.yml
This bumps omero-web on nightshade, demo-server, training-server and sls-gallery.
> Bump omero_web_release to 5.14.1 everywhere

- omero/training-server/playbook.yml
In exploration of adding of public user to outreach server via omero web config.
Does not work very well atm. When a new public user is created, and a new public group, the Dataset inside that group is not publicly visible, e.g. https://ome-training-4.openmicroscopy.org/webclient/?show=dataset-5405
Not sure where the mistake is.
cc @jburel @sbesson
> Add public user to web config

- omero/training-server/playbook.yml
Successfully deployed on 
- ome-training-4
- outreach
- workshop
but not on ome-training-3. This server is left out intentionally for https://github.com/ome/prod-playbooks/pull/349 testing
> Upgrade web and download figure publish scripts

- omero/training-server/playbook.yml
See https://github.com/ome/prod-playbooks/issues/353 for background.
@sbesson I am afraid the suggested change as implemented in this PR and tested on ome-training-4 is causing "No processor available" when trying to run a script (Batch image export).
> Disable PixelData

- omero/training-server/playbook.yml
Upgrading the training servers to OMERO.server 5.6.5.
Successfully applied to all 4 training servers, see below.
cc @sbesson 
```
2022-07-04 14:25:52,489 184        [      main] INFO          ome.formats.importer.ImportConfig - OMERO.blitz Version: 5.5.12
2022-07-04 14:25:52,505 200        [      main] INFO          ome.formats.importer.ImportConfig - Bioformats version: 6.10.0 revision: f8b46c2458c43cffdf5bc67cc4bf9dfc6e93167b date: 31 May 2022
2022-07-04 14:25:52,546 241        [      main] INFO   formats.importer.cli.CommandLineImporter - Setting transfer to ln_s
2022-07-04 14:25:52,550 245        [      main] INFO   formats.importer.cli.CommandLineImporter - Log levels -- Bio-Formats: ERROR OMERO.importer: INFO
2022-07-04 14:25:52,888 583        [      main] INFO …
```
> Upgrade OMERO.server on training-servers to 5.6.5

- omero/nightshade-webclients.yml
- omero/ome-demoserver.yml
- omero/ome-dundeeomero.yml
- omero/training-server/playbook.yml
Bump OMERO.figure version to latest 5.0.0 everywhere.
cc @pwalczysko
> Bump omero_figure_release to 5.0.0 everywhere

- omero/learning.yml
- omero/nightshade-webclients.yml
- omero/ome-demoserver.yml
- omero/sls-gallery.yml
- omero/training-server/playbook.yml
Updating recent releases of omero-web and omero-py (which needs to use `omero_web_python_addons`)
cc @sbesson @pwalczysko
> Omeropy 5.12.0 web 5.15

- omero/ome-demoserver.yml
As discussed, disabling pixels on demo, see discussion in https://openmicroscopy.slack.com/archives/C0K5ME1EW/p1668597336544119
cc @sbesson @jburel 
This was run agains demoserver successfully
```
omero admin diagnostics
================================================================================
OMERO Diagnostics (admin) 5.12.0
================================================================================
Commands:   java -version                  1.8.0     (/usr/bin/java)
Commands:   python -V                      3.6.8     (/opt/omero/server/venv3/bin/python -- 2 others)
Commands:   icegridnode --version          3.6.5     (/usr/bin/icegridnode)
Commands:   icegridadmin --version         3.6.5     (/usr/bin/icegridadmin)
Commands:   psql --version                 11.14 …
```
> Disable pixelservice on demo server

- omero/learning.yml
- omero/nightshade-webclients.yml
- omero/ome-demoserver.yml
- omero/ome-dundeeomero.yml
- omero/training-server/playbook.yml
Upgrades:
1. server 5.6.6
2. web 5.16.0
3. figure
4. iviewer
5. omero-py 5.13.1
Further:
- adding logic to each playbook to upgrade to latest omero-py when server is upgraded - please check this one @sbesson 
This was deployed on 
cc @jburel
> Upgrade 5.6.6 and other bumps

- omero/ome-demoserver.yml
Upgrading the cleanup script on the demo server.
Now, only the ``. /opt/omero/server/venv3/bin/activate`` is necessary to be able to run the script.
This PR is necessary as the venv established in the home folders of @dominikl @pwalczysko and @khaledk2 were taking too much space on the root partition of the server.
This was run successfully on demo server.
cc @sbesson @jburel
> Upgrade demo cleanup script
